DROP TABLE IF EXISTS Task CASCADE;
DROP TABLE IF EXISTS UserTask CASCADE;
DROP TABLE IF EXISTS TaskStatusType CASCADE;
DROP TABLE IF EXISTS TaskStatus CASCADE;
DROP TABLE IF EXISTS tasktree CASCADE;
DROP TABLE IF EXISTS subtask CASCADE;
DROP TABLE IF EXISTS taskonuser CASCADE;
DROP TABLE IF EXISTS taskongroup CASCADE;

DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS subject CASCADE;
DROP TABLE IF EXISTS "group" CASCADE;

DROP TABLE IF EXISTS permission CASCADE;
DROP TABLE IF EXISTS rolepermissions CASCADE;
DROP TABLE IF EXISTS groupmemberroles CASCADE;
DROP TABLE IF EXISTS groupmember CASCADE;
DROP TABLE IF EXISTS userroles CASCADE;
DROP TABLE IF EXISTS role CASCADE;

DROP TABLE IF EXISTS usertoken CASCADE;

DROP TABLE IF EXISTS usertask CASCADE;

DROP TABLE IF EXISTS apptoken CASCADE;
DROP TABLE IF EXISTS registeredapp CASCADE;