http:
  port: 8080
  readTimeout: 10s
  writeTimeout: 10s

postgres:
  url: "host=10.0.0.12 dbname=apiserver_unitask user=postgres password=postgres sslmode=disable connect_timeout=5"
  name: apiserver_unitask

auth:
  appTokenTTL: 30d
  accessTokenTTL: 2h
  refreshTokenTTL: 720h
  signingKey: startKey

limiter:
  rps: 10

