http:
  port: 8080
  readTimeout: 10s
  writeTimeout: 10s

postgres:
  name: apiserver_unitask

auth:
  appTokenTTL: 2160h
  jwt:
    accessTokenTTL: 2h
    refreshTokenTTL: 720h
    signingKey: startKey

limiter:
  rps: 10

